#ifndef ERRORCODEANDMSG_LIB_GLOBAL_H
#define ERRORCODEANDMSG_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ERRORCODEANDMSG_LIB_LIBRARY)
#  define ERRORCODEANDMSG_LIB_EXPORT Q_DECL_EXPORT
#else
#  define ERRORCODEANDMSG_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif // ERRORCODEANDMSG_LIB_GLOBAL_H
