#ifndef ELAPSEDTIME_LIB_GLOBAL_H
#define ELAPSEDTIME_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ELAPSEDTIME_LIB_LIBRARY)
#  define ELAPSEDTIME_LIB_EXPORT Q_DECL_EXPORT
#else
#  define ELAPSEDTIME_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif // ELAPSEDTIME_LIB_GLOBAL_H
